stages:
  - build

variables:
  IMAGE_NAME: $CI_REGISTRY_IMAGE:latest

before_script:
  - env
  - docker info
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  stage: build
  script:
  - git clone --depth 1 https://github.com/EFForg/congress_forms
  - git clone --depth 1 https://github.com/unitedstates/contact-congress contact_congress
  - docker build --pull --no-cache --label "repo=$CI_PROJECT_URL" -t $IMAGE_NAME .
  - docker push $IMAGE_NAME
  only:
  - master
