default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV["DATABASE_HOST"] %>
  username: <%= ENV["DATABASE_USER"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>

test:
  <<: *default
  database: congress_forms_api_test

development:
  <<: *default
  database: congress_forms_api_development

production:
  <<: *default
  database: congress_forms_api_production
